# docker-compose.yml
version: '3'

services:
  flask-api:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ollama_data:/root/.ollama

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - flask-api

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
